"""added_unique_constraints

Revision ID: 2d45226e8595
Revises: 
Create Date: 2026-09-22 20:22:57.674235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d45226e8595'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diseases',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_diseases')),
    sa.UniqueConstraint('name', name=op.f('uq_diseases_name'))
    )
    op.create_table('employees',
    sa.Column('login', sa.String(length=15), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('role', sa.Enum('DOCTOR', 'ADMIN', name='role'), nullable=False),
    sa.Column('speciality', sa.String(length=50), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employees'))
    )
    op.create_table('medicines',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('properties', sa.String(), nullable=False),
    sa.Column('side_effects', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_medicines')),
    sa.UniqueConstraint('name', name=op.f('uq_medicines_name'))
    )
    op.create_table('patients',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('sex', sa.Enum('MALE', 'FEMALE', name='sex'), nullable=False),
    sa.Column('born_date', sa.Date(), nullable=False),
    sa.Column('home_address', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_patients'))
    )
    op.create_table('inspections',
    sa.Column('date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('symptoms', sa.String(), nullable=False),
    sa.Column('instructions', sa.String(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['employees.id'], name=op.f('fk_inspections_doctor_id_employees'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_inspections_patient_id_patients'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inspections'))
    )
    op.create_table('inspectiondiseases',
    sa.Column('inspection_id', sa.Integer(), nullable=False),
    sa.Column('disease_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['disease_id'], ['diseases.id'], name=op.f('fk_inspectiondiseases_disease_id_diseases'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], name=op.f('fk_inspectiondiseases_inspection_id_inspections'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inspectiondiseases'))
    )
    op.create_table('prescriptions',
    sa.Column('inspection_id', sa.Integer(), nullable=False),
    sa.Column('medicine_id', sa.Integer(), nullable=False),
    sa.Column('intake_method', sa.String(), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], name=op.f('fk_prescriptions_inspection_id_inspections'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicines.id'], name=op.f('fk_prescriptions_medicine_id_medicines'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prescriptions')),
    sa.UniqueConstraint('inspection_id', 'medicine_id', 'intake_method', name='idx_unique_inspection_medicine_intake')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prescriptions')
    op.drop_table('inspectiondiseases')
    op.drop_table('inspections')
    op.drop_table('patients')
    op.drop_table('medicines')
    op.drop_table('employees')
    op.drop_table('diseases')
    # ### end Alembic commands ###
