"""medicine_sdd_side_effects_row_prescription_del_side_effects_added_note_instead

Revision ID: b9816955aca2
Revises: 820c4d3d88df
Create Date: 2026-09-21 19:40:14.593735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9816955aca2'
down_revision: Union[str, Sequence[str], None] = '820c4d3d88df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
