"""server_default

Revision ID: f796d3c7d762
Revises: b3b4ec25f164
Create Date: 2026-09-28 10:30:52.599624

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "f796d3c7d762"
down_revision: str | Sequence[str] | None = "b3b4ec25f164"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
