"""changes_in_inspection_disease_table_inspection_id_and_disease_id_is_unique

Revision ID: b29e7753a275
Revises: dcd19cdadc6f
Create Date: 2026-09-23 14:03:45.586671

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b29e7753a275"
down_revision: str | Sequence[str] | None = "dcd19cdadc6f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("inspectiondiseases", schema=None) as batch_op:
        batch_op.create_unique_constraint(
            batch_op.f("uq_inspectiondiseases_inspection_id_disease_id"),
            ["inspection_id", "disease_id"],
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("inspectiondiseases", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("uq_inspectiondiseases_inspection_id_disease_id"), type_="unique"
        )

    # ### end Alembic commands ###
