"""added_row_updated_at_in_prescription

Revision ID: 2f2cc4b7af6f
Revises: f796d3c7d762
Create Date: 2026-10-02 11:39:16.372028

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2f2cc4b7af6f"
down_revision: str | Sequence[str] | None = "f796d3c7d762"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("prescriptions", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "updated_at",
                sa.DateTime(),
                server_default=sa.text("(CURRENT_TIMESTAMP)"),
                nullable=True,
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("prescriptions", schema=None) as batch_op:
        batch_op.drop_column("updated_at")

    # ### end Alembic commands ###
