"""table_patient_unum_changed_to_str_like

Revision ID: 60d4c46c9737
Revises: b660f1c0d88e
Create Date: 2026-09-22 19:05:07.932274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60d4c46c9737'
down_revision: Union[str, Sequence[str], None] = 'b660f1c0d88e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
