"""changes_in_employee_table_login_is_unique

Revision ID: dcd19cdadc6f
Revises: c91885cf9c93
Create Date: 2026-09-23 14:00:11.209928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcd19cdadc6f'
down_revision: Union[str, Sequence[str], None] = 'c91885cf9c93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_employees_login'), ['login'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_employees_login'), type_='unique')

    # ### end Alembic commands ###
